"""Entropy GC Workflow — daily scan + cleanup PR generation.

Runs the cleaner agent against lint output, clusters auto-fixable violations,
opens one atomic PR per cluster, updates QUALITY_SCORE.md.

Schedule: daily via .github/workflows/entropy_gc.yml
"""

import subprocess
from datetime import datetime
from pathlib import Path
from typing import TypedDict

import logfire
from langgraph.graph import END, StateGraph

from agents.models.cleaner import CleanupOutput, EntropyViolation
from agents.tools.git import commit, open_pr
from agents.tools.shell import run_lint
from agents.workers.cleaner import run_cleaner


class GCState(TypedDict):
    scan_report: str
    cleanup: CleanupOutput | None
    prs_opened: list[str]
    quality_score_updated: bool


def _repo_root() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True
    )
    return Path(result.stdout.strip())


def _collect_domains() -> list[str]:
    root = _repo_root()
    return [
        d.name for d in root.iterdir()
        if d.is_dir() and not d.name.startswith(".") and d.name != "__pycache__"
    ]


async def entropy_scan_node(state: GCState) -> dict:
    """Run all linters and collect a comprehensive scan report."""
    lint_result = run_lint.fn(".")  
    violations_text = "\n".join(lint_result.violations) if lint_result.violations else "No violations"
    scan_report = f"Lint violations:\n{violations_text}\n\nAuto-fixed: {lint_result.auto_fixed}"
    return {"scan_report": scan_report}


async def analyze_violations_node(state: GCState) -> dict:
    """Run the cleaner agent to analyze violations."""
    domains = _collect_domains()
    cleanup = await run_cleaner(state["scan_report"], domains)
    return {"cleanup": cleanup}


def _cluster_violations(violations: list[EntropyViolation]) -> dict[str, list[EntropyViolation]]:
    """Group violations by principle for atomic PRs."""
    clusters: dict[str, list[EntropyViolation]] = {}
    for v in violations:
        if v.auto_fixable:
            key = v.principle
            clusters.setdefault(key, []).append(v)
    return clusters


async def open_cleanup_prs_node(state: GCState) -> dict:
    """Open one PR per auto-fixable violation cluster."""
    if not state["cleanup"]:
        return {"prs_opened": []}

    clusters = _cluster_violations(state["cleanup"].violations)
    prs_opened = []

    for principle, violations in clusters.items():
        files = list({v.file for v in violations})
        body = f"## Entropy GC — {principle}\n\n"
        body += "**Violations:**\n"
        for v in violations:
            body += f"- `{v.file}`: {v.description}\n"
        body += "\n**Auto-generated by entropy_gc workflow.**\n"
        body += "\n_This PR is auto-mergeable if tests pass._"

        title = f"[gc] {principle}: {violations[0].description[:60]}"

        pr_result = await open_pr.fn(title=title, body=body)  
        if pr_result.success:
            prs_opened.append(pr_result.url)
            logfire.info("gc_pr_opened", principle=principle, url=pr_result.url)

    return {"prs_opened": prs_opened}


async def update_quality_score_node(state: GCState) -> dict:
    """Write updated QUALITY_SCORE.md based on cleanup analysis."""
    if not state["cleanup"]:
        return {"quality_score_updated": False}

    cleanup = state["cleanup"]
    root = _repo_root()
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# QUALITY_SCORE.md — Per-Domain Quality Grades",
        "",
        f"> Auto-updated by entropy GC workflow. Last updated: {now}",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Domain | Score | Violations |",
        "|---|---|---|",
    ]

    for domain, score in sorted(cleanup.quality_scores.items()):
        domain_violations = sum(1 for v in cleanup.violations if domain in v.file)
        trend = "10.0" if score == 10.0 else f"{score:.1f}"
        lines.append(f"| {domain} | {trend} | {domain_violations} |")

    overall = cleanup.overall_score()
    lines.extend([
        "",
        f"**Overall: {overall:.1f} / 10.0**",
        "",
        "---",
        "",
        "## Active Violations",
        "",
    ])

    if cleanup.violations:
        for v in cleanup.violations:
            auto = "auto-fixable" if v.auto_fixable else "needs human"
            lines.append(f"- **{v.principle}** [{v.severity}] `{v.file}`: {v.description} ({auto})")
    else:
        lines.append("No violations detected.")

    lines.extend([
        "",
        "## PRs Opened This Run",
        "",
    ])
    for pr_url in state["prs_opened"]:
        lines.append(f"- {pr_url}")

    score_path = root / "docs" / "QUALITY_SCORE.md"
    score_path.write_text("\n".join(lines) + "\n")

    # Commit the updated score
    commit_result = await commit.fn(  # type: ignore[attr-defined]
        message=f"chore(gc): update quality scores [{now}]",
        files=["docs/QUALITY_SCORE.md"],
    )

    return {"quality_score_updated": commit_result.success}


def build_gc_graph() -> StateGraph:
    graph = StateGraph(GCState)

    graph.add_node("entropy_scan_node", entropy_scan_node)
    graph.add_node("analyze_violations_node", analyze_violations_node)
    graph.add_node("open_cleanup_prs_node", open_cleanup_prs_node)
    graph.add_node("update_quality_score_node", update_quality_score_node)

    graph.set_entry_point("entropy_scan_node")
    graph.add_edge("entropy_scan_node", "analyze_violations_node")
    graph.add_edge("analyze_violations_node", "open_cleanup_prs_node")
    graph.add_edge("open_cleanup_prs_node", "update_quality_score_node")
    graph.add_edge("update_quality_score_node", END)

    return graph


async def run_entropy_gc(update_scores_only: bool = False) -> GCState:
    """Run the entropy GC workflow. Returns final state."""
    with logfire.span("entropy_gc"):
        graph = build_gc_graph()
        app = graph.compile()

        state = GCState(
            scan_report="",
            cleanup=None,
            prs_opened=[],
            quality_score_updated=False,
        )
        final = await app.ainvoke(state)

        logfire.info(
            "entropy_gc_complete",
            violations=len(final["cleanup"].violations) if final["cleanup"] else 0,
            prs_opened=len(final["prs_opened"]),
            quality_score_updated=final["quality_score_updated"],
            overall_score=final["cleanup"].overall_score() if final["cleanup"] else 10.0,
        )
        return final


if __name__ == "__main__":
    import asyncio
    import sys
    update_only = "--update-scores-only" in sys.argv
    asyncio.run(run_entropy_gc(update_scores_only=update_only))
