"""Entropy GC Workflow — daily scan + cleanup PR generation.

Runs the cleaner agent against lint output, clusters auto-fixable violations,
opens one atomic PR per cluster, updates QUALITY_SCORE.md.

Schedule: daily via .github/workflows/entropy_gc.yml
"""

from datetime import UTC, datetime
from typing import Any, TypedDict

import logfire
from langgraph.graph import END, StateGraph

from agents.core.guards import pre_node_guard
from agents.core.paths import repo_root as _repo_root
from agents.core.workflow_helpers import (
    accumulate_usage,
    apply_file_changes,
    update_node_tool_calls,
)
from agents.models.cleaner import CleanupOutput, EntropyViolation
from agents.models.implementer import FileChange
from agents.tools.git import commit, open_pr
from agents.tools.shell import run_lint
from agents.workers.cleaner import run_cleaner


class GCState(TypedDict):
    scan_report: str
    cleanup: CleanupOutput | None
    prs_opened: list[str]
    quality_score_updated: bool
    status: str
    error_log: list[str]
    total_tool_calls: int
    node_tool_calls: dict[str, int]
    estimated_cost_usd: float


def _collect_domains() -> list[str]:
    root = _repo_root()
    return [
        d.name
        for d in root.iterdir()
        if d.is_dir() and not d.name.startswith(".") and d.name != "__pycache__"
    ]


async def entropy_scan_node(state: GCState) -> dict[str, Any]:
    """Run all linters and collect a comprehensive scan report."""
    guard = pre_node_guard(state, "entropy_scan_node")
    if not guard.allowed:
        return {"status": "failed", "error_log": state["error_log"] + [guard.reason]}

    lint_result = run_lint(".")
    violations_text = (
        "\n".join(lint_result.violations) if lint_result.violations else "No violations"
    )
    scan_report = f"Lint violations:\n{violations_text}\n\nAuto-fixed: {lint_result.auto_fixed}"
    node_calls = 1
    return {
        "scan_report": scan_report,
        "total_tool_calls": state["total_tool_calls"] + node_calls,
        "node_tool_calls": update_node_tool_calls(state, "entropy_scan_node", node_calls),
    }


async def analyze_violations_node(state: GCState) -> dict[str, Any]:
    """Run the cleaner agent to analyze violations."""
    guard = pre_node_guard(state, "analyze_violations_node")
    if not guard.allowed:
        return {"status": "failed", "error_log": state["error_log"] + [guard.reason]}

    domains = _collect_domains()
    cleanup, usage = await run_cleaner(state["scan_report"], domains)
    node_calls = 1  # run_cleaner
    return {
        "cleanup": cleanup,
        **accumulate_usage(state, usage, "analyze_violations_node", node_calls),
        "total_tool_calls": state["total_tool_calls"] + node_calls,
    }


def _cluster_violations(violations: list[EntropyViolation]) -> dict[str, list[EntropyViolation]]:
    """Group violations by principle for atomic PRs."""
    clusters: dict[str, list[EntropyViolation]] = {}
    for v in violations:
        if v.auto_fixable:
            key = v.principle
            clusters.setdefault(key, []).append(v)
    return clusters


async def open_cleanup_prs_node(state: GCState) -> dict[str, Any]:
    """Open one tracking PR per auto-fixable violation cluster.

    NOTE: This node opens PRs that describe the violations to fix, but does not
    implement the fixes itself. The actual fix implementation is handled by
    running Ralph Loop on each PR's description as a task.
    """
    guard = pre_node_guard(state, "open_cleanup_prs_node")
    if not guard.allowed:
        return {"status": "failed", "error_log": state["error_log"] + [guard.reason]}

    if not state["cleanup"]:
        return {
            "prs_opened": [],
            "total_tool_calls": state["total_tool_calls"],
            "node_tool_calls": state["node_tool_calls"],
        }

    clusters = _cluster_violations(state["cleanup"].violations)
    prs_opened = []
    attempts = 0

    for principle, violations in clusters.items():
        affected_files = sorted({v.file for v in violations})
        body = f"## Entropy GC — {principle}\n\n"
        body += f"**Affected files:** {', '.join(f'`{f}`' for f in affected_files)}\n\n"
        body += "**Violations:**\n"
        for v in violations:
            body += f"- `{v.file}`: {v.description}\n"
        body += "\n**Auto-generated by entropy_gc workflow.**\n"
        body += "\n_This PR is auto-mergeable if tests pass._"

        title = f"[gc] {principle}: {violations[0].description[:60]}"

        attempts += 1
        pr_result = open_pr(title=title, body=body)
        if pr_result.success:
            prs_opened.append(pr_result.url)
            logfire.info("gc_pr_opened", principle=principle, url=pr_result.url)

    return {
        "prs_opened": prs_opened,
        "total_tool_calls": state["total_tool_calls"] + attempts,
        "node_tool_calls": update_node_tool_calls(state, "open_cleanup_prs_node", attempts),
    }


async def update_quality_score_node(state: GCState) -> dict[str, Any]:
    """Write updated QUALITY_SCORE.md based on cleanup analysis."""
    guard = pre_node_guard(state, "update_quality_score_node")
    if not guard.allowed:
        return {"status": "failed", "error_log": state["error_log"] + [guard.reason]}

    if not state["cleanup"]:
        return {
            "quality_score_updated": False,
            "total_tool_calls": state["total_tool_calls"],
            "node_tool_calls": state["node_tool_calls"],
        }

    cleanup = state["cleanup"]
    root = _repo_root()
    now = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# QUALITY_SCORE.md — Per-Domain Quality Grades",
        "",
        f"> Auto-updated by entropy GC workflow. Last updated: {now}",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Domain | Score | Violations |",
        "|---|---|---|",
    ]

    for domain, score in sorted(cleanup.quality_scores.items()):
        domain_violations = sum(1 for v in cleanup.violations if domain in v.file)
        trend = "10.0" if score == 10.0 else f"{score:.1f}"
        lines.append(f"| {domain} | {trend} | {domain_violations} |")

    overall = cleanup.overall_score()
    lines.extend(
        [
            "",
            f"**Overall: {overall:.1f} / 10.0**",
            "",
            "---",
            "",
            "## Active Violations",
            "",
        ]
    )

    if cleanup.violations:
        for v in cleanup.violations:
            auto = "auto-fixable" if v.auto_fixable else "needs human"
            lines.append(f"- **{v.principle}** [{v.severity}] `{v.file}`: {v.description} ({auto})")
    else:
        lines.append("No violations detected.")

    lines.extend(
        [
            "",
            "## PRs Opened This Run",
            "",
        ]
    )
    for pr_url in state["prs_opened"]:
        lines.append(f"- {pr_url}")

    apply_file_changes(
        [
            FileChange(
                path="docs/QUALITY_SCORE.md",
                content="\n".join(lines) + "\n",
                operation="modify",
                diff_summary="Update quality scores and PR list",
            ),
        ],
        root=root,
    )

    commit_result = commit(
        message=f"chore(gc): update quality scores [{now}]",
        files=["docs/QUALITY_SCORE.md"],
    )

    node_calls = 1
    return {
        "quality_score_updated": commit_result.success,
        "total_tool_calls": state["total_tool_calls"] + node_calls,
        "node_tool_calls": update_node_tool_calls(state, "update_quality_score_node", node_calls),
    }


def _gc_status_gate(state: GCState, next_node: str) -> str:
    """Route to END on failure, otherwise continue."""
    if state.get("status") == "failed":
        return END
    return next_node


def _route_after_scan(state: GCState) -> str:
    return _gc_status_gate(state, "analyze_violations_node")


def _route_after_analyze(state: GCState) -> str:
    return _gc_status_gate(state, "open_cleanup_prs_node")


def _route_after_analyze_scores_only(state: GCState) -> str:
    return _gc_status_gate(state, "update_quality_score_node")


def _route_after_open_prs(state: GCState) -> str:
    return _gc_status_gate(state, "update_quality_score_node")


def build_gc_graph() -> StateGraph:
    graph = StateGraph(GCState)

    graph.add_node("entropy_scan_node", entropy_scan_node)
    graph.add_node("analyze_violations_node", analyze_violations_node)
    graph.add_node("open_cleanup_prs_node", open_cleanup_prs_node)
    graph.add_node("update_quality_score_node", update_quality_score_node)

    graph.set_entry_point("entropy_scan_node")
    graph.add_conditional_edges("entropy_scan_node", _route_after_scan)
    graph.add_conditional_edges("analyze_violations_node", _route_after_analyze)
    graph.add_conditional_edges("open_cleanup_prs_node", _route_after_open_prs)
    graph.add_edge("update_quality_score_node", END)

    return graph


def build_scores_only_graph() -> StateGraph:
    """Graph that scans and updates quality scores but does not open PRs."""
    graph = StateGraph(GCState)
    graph.add_node("entropy_scan_node", entropy_scan_node)
    graph.add_node("analyze_violations_node", analyze_violations_node)
    graph.add_node("update_quality_score_node", update_quality_score_node)
    graph.set_entry_point("entropy_scan_node")
    graph.add_conditional_edges("entropy_scan_node", _route_after_scan)
    graph.add_conditional_edges("analyze_violations_node", _route_after_analyze_scores_only)
    graph.add_edge("update_quality_score_node", END)
    return graph


async def run_entropy_gc(update_scores_only: bool = False) -> GCState:
    """Run the entropy GC workflow. Returns final state."""
    with logfire.span("entropy_gc", update_scores_only=update_scores_only):
        graph = build_scores_only_graph() if update_scores_only else build_gc_graph()
        app = graph.compile()

        state = GCState(
            scan_report="",
            cleanup=None,
            prs_opened=[],
            quality_score_updated=False,
            status="running",
            error_log=[],
            total_tool_calls=0,
            node_tool_calls={},
            estimated_cost_usd=0.0,
        )
        final = await app.ainvoke(state)

        logfire.info(
            "entropy_gc_complete",
            violations=len(final["cleanup"].violations) if final["cleanup"] else 0,
            prs_opened=len(final["prs_opened"]),
            quality_score_updated=final["quality_score_updated"],
            overall_score=final["cleanup"].overall_score() if final["cleanup"] else 10.0,
        )
        return final


if __name__ == "__main__":
    import asyncio
    import sys

    update_only = "--update-scores-only" in sys.argv
    asyncio.run(run_entropy_gc(update_scores_only=update_only))
