"""Post-mortem node — analyzes failures and creates harness-improvement issues.

Extracted from ralph_loop to stay under GP-002 (500 lines). Wired into the
ralph_loop graph after human_checkpoint.
"""

from typing import Any

import logfire

from agents.core.state import RalphState
from agents.models.cost import TokenUsage
from agents.tools.git import create_issue
from agents.workers.post_mortem import run_post_mortem


def _accumulate_usage(state: RalphState, usage: TokenUsage, node_name: str) -> dict:
    """Return state updates for token/cost accumulation."""
    prev = state["node_token_usage"].get(node_name, {"tokens_in": 0, "tokens_out": 0})
    updated = dict(state["node_token_usage"])
    updated[node_name] = {
        "tokens_in": prev["tokens_in"] + usage.tokens_in,
        "tokens_out": prev["tokens_out"] + usage.tokens_out,
    }
    return {
        "total_tokens_in": state["total_tokens_in"] + usage.tokens_in,
        "total_tokens_out": state["total_tokens_out"] + usage.tokens_out,
        "estimated_cost_usd": state["estimated_cost_usd"] + usage.cost_usd(),
        "node_token_usage": updated,
    }


async def post_mortem_node(state: RalphState) -> dict[str, Any]:
    """Analyze failure and create a harness-improvement issue."""
    validation_summary = None
    if state["validation"]:
        v = state["validation"]
        parts = []
        if not v.tests.passed:
            parts.append(f"Test failures: {', '.join(v.tests.failures[:5])}")
        if not v.lint.passed:
            parts.append(f"Lint violations: {', '.join(v.lint.violations[:5])}")
        if not v.arch_lint.passed:
            parts.append(f"Arch violations: {', '.join(v.arch_lint.violations[:5])}")
        if v.failure_summary:
            parts.append(v.failure_summary)
        validation_summary = "\n".join(parts) if parts else None

    guard_reasons = [e for e in state["error_log"] if "guard" in e.lower() or "max" in e.lower()]

    try:
        analysis, usage = await run_post_mortem(
            task=state["task"],
            error_log=state["error_log"],
            iteration_count=state["iteration_count"],
            review_iteration_count=state["review_iteration_count"],
            estimated_cost_usd=state["estimated_cost_usd"],
            validation_summary=validation_summary,
            guard_reasons=guard_reasons,
        )
    except Exception as e:
        logfire.warning("post_mortem_failed", error=str(e))
        return {}

    issue_body = (
        f"## Failure Analysis\n\n"
        f"**Category:** `{analysis.category}`\n"
        f"**Priority:** `{analysis.priority}`\n"
        f"**Task:** {state['task'][:200]}\n\n"
        f"### What went wrong\n{analysis.failure_summary}\n\n"
        f"### Root cause\n{analysis.root_cause}\n\n"
        f"### Affected files\n"
        + "\n".join(f"- `{f}`" for f in analysis.affected_files)
        + f"\n\n### Recommended improvement\n{analysis.improvement}\n\n"
        f"### Suggested fix\n```\n{analysis.suggested_fix}\n```\n\n"
        f"---\n_Auto-generated by Ouroboros post-mortem analysis._"
    )

    issue_result = create_issue(
        title=f"harness: {analysis.improvement[:72]}",
        body=issue_body,
        labels=["harness-improvement"],
    )

    issue_url = issue_result.url if issue_result.success else None
    if issue_result.success:
        logfire.info(
            "post_mortem_issue_created",
            issue_url=issue_url,
            category=analysis.category,
            priority=analysis.priority,
        )
    else:
        logfire.warning("post_mortem_issue_failed", error=issue_result.error)

    return {
        "post_mortem": analysis,
        "improvement_issue_url": issue_url,
        **_accumulate_usage(state, usage, "post_mortem_node"),
        "total_tool_calls": state["total_tool_calls"] + 2,
    }
